apiVersion: v1
kind: Service
metadata:
   name: db-svc
   namespace: odoo
   labels:
      app: odoo-db
spec:
   ports:
   - name: odoo-db
     port: 31650
     targetPort: db-port
   selector:
     app: odoo-db     
