apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-pgsql
  namespace: odoo
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
